### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by Feriman22** [greensheep/plex-server-docker-rpi#26]
Hi,

Can you create a docker-compose.yml file instead of the docker run command? It might make things easier, especially when using portainer.

Thanks,
Feriman

**Comment by Feriman22** [comment]
Meanwhile I wrote the docker compose file :)

```
version: '3'
services:
  plex:
    image: greensheep/plex-server-docker-rpi:latest
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400"
    restart: always
    volumes:
      - "${HOME}/media/plex/config:/config"
      - "${HOME}/media/plex/data:/data"
```
